name: Secure Website CI/CD Pipeline 

on:
  push:
    branches:
      - main 

permissions:
  id-token: write 
  contents: read 

jobs:

  security_scan:
    name: "Automated SecOps Guardrails"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0 

      - name: Run Gitleaks Secret Audit 
        uses: gitleaks/gitleaks-action@v2 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Checkov IaC Compliance Scan 
        uses: bridgecrewio/checkov-action@master 
        with: 
          directory: 'infrastructure/'
          framework: 'terraform' 
          soft_fail: false 
          skip_check: >
            CKV2_AWS_34,
            CKV2_AWS_31,
            CKV_AWS_144,
            CKV2_AWS_42,
            CKV_AWS_145,
            CKV2_AWS_65,
            CKV2_AWS_61,
            CKV_AWS_18,
            CKV2_AWS_62,
            CKV2_AWS_47
          
  deploy: 
    name: Fetch Context & Sync Assets 
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code Repo 
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Configure AWS Creds via Secure OIDC 
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with: 
          role-to-assume: ${{ vars.AWS_ROLE_ARN}} 
          aws-region: us-east-1 
          audience: sts.amazonaws.com 

      - name: Progammatically Fecth Live Settings from AWS SSM 
        id: ssm_fetch 
        run: |
          echo "Querying dynamic runtime configurations from AWS Systems Manager..." 

          BUCKET=$(aws ssm get-parameter --name "/config/production/cloudpipe/cicd_website_bucket" --query "Parameter.Value" --output text) 
          DIST_ID=$(aws ssm get-parameter --name "/config/production/cloudpipe/cloudfront_distribution_id" --query "Parameter.Value" --output text)

          echo "::add-mask::$BUCKET"
          echo "::add-mask::$DIST_ID"

          echo "s3_bucket=$BUCKET" >> $GITHUB_OUTPUT 
          echo "cloudfront_id=$DIST_ID" >> $GITHUB_OUTPUT 

      - name: Synchronize Static App Assets to Private S3 
        run: | 
          aws s3 sync ./website/ s3://${{ steps.ssm_fetch.outputs.s3_bucket}} --delete 

      - name: Invalidate Cloudfront Global Cache Edge Points 
        run: | 
          aws cloudfront create-invalidation --distribution-id ${{ steps.ssm_fetch.outputs.cloudfront_id}} --paths "/*" 

      - name: Terraform Apply 
        id: tf_apply 
        run: | 
          cd infrastructure 
          terraform apply -auto-approve

      - name: Capture Live Endpoint URL 
        id: capture_url 
        run: | 
          cd infrastructure 
          URL=$(terraform output -raw cloudfront_domain) 
          echo "LIVE_URL=https://$URL" >> $GITHUB_ENV 

      - name: Run Nuclei DAST Scan 
        uses: projectdiscovery/nuclei-action@v3
        with:
          args: "-u ${{ env.LIVE_URL }} -severity critical,high -output nuclei-report.txt -silent"

      - name: Secure Scan Report Artifact 
        uses: actions/upload-artifact@v4 
        with: 
          name: nuclei-security-report 
          retention-days: 7 
          overwrite: true 

  